# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TweetImage3
                                 A QGIS plugin
 Tweet your map canvas (updated for QGIS 3)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-06
        copyright            : (C) 2019 by Al Graham
        email                : llansteffan@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TweetImage3 class from file TweetImage3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tweetimage3 import TweetImage3
    return TweetImage3(iface)
